### PR TITLE
remove lemmas that likely unneeded

### PR DESCRIPTION
**Pull request by kmbarry1**
I ran a good percentage (not all) of the proofs locally. Got one failure (`DssCdpManager_open_fail_rough`) which I am looking into, but going ahead an opening this PR just to keep track of the work and to coordinate any collaboration.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
Ok this is great. I'm reviewing which proofs are passing with the newer `klab` version but still old lemmas.
So far is being the same than before.

So for reference, with the older `klab` and all the lemmas, every proof of the actual `act`s were being accepted excepting:

- `DssCdpManager_give-diff-own-dst_pass_rough`
- `DssCdpManager_give-diff-own-dst_fail_rough`
- `DssCdpManager_frob-nonzero_fail_rough`
- `DssCdpManager_frob-zero-dink_fail_rough`

**Comment by kmbarry1** [comment]
re-ran `DssCdpManager_open_fail_rough` and it accepted, not sure what happened the first time

**Comment by gbalabasquer** [comment]
Ok good to know, it's still running here (still with lemmas but latest klab) and so far keeps having the same behaviour.

**Comment by gbalabasquer** [comment]
I had `DssCdpManager_open_fail_rough` being accepted without any issue but `DssCdpManager_open_pass_rough` rejected. I'll run it again with `--dump` later and report findings. For now all the rest of accepted proofs keep doing it. I have tested 50% aprox.

**Pull request merged**
